name: Release notifications
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
    - name: Telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          TzKT ${{ env.RELEASE_VERSION }} has been released 😻
          Docker images will be available in a few minutes.
          More info at https://github.com/baking-bad/tzkt/releases/tag/${{ env.RELEASE_VERSION }}
    - name: Slack notification
      uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: |
          TzKT ${{ env.RELEASE_VERSION }} has been released 😻
          Docker images will be available in a few minutes.
          More info at https://github.com/baking-bad/tzkt/releases/tag/${{ env.RELEASE_VERSION }}
